### ISSUE TITLE
Form Initial Steering Committee 

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/charter#7]
We need to form an initial steering committee. So far, we have a few volunteers:
- @gianugo or @jeffmcaffer  (Microsoft)
- @fallenpegasus (HP)
- @amateurhuman or @bkeepers (GitHub)
- @gyehuda (Yahoo)
- @caniszczyk (LF)

Potential invited members that aren't part of TODO Group yet:
- Nithya A. Ruff (SanDisk)

**Comment by lfaraone** [comment]
also throwing my name in.

**Comment by DuaneOBrien** [comment]
Registering my interest as well.

**Comment by guywmartin** [comment]
Tossing my hat into the ring as well. :)

**Comment by jimjag** [comment]
ditto

**Comment by nruff** [comment]
Adding my name to this respected group. 

Excuse my typos and autocorrects.
Thank you,  
Nithya Ruff

**Comment by jaredsmith** [comment]
I'll throw my hat in the ring as well.

**Comment by caniszczyk** [comment]
thanks, final call for folks before I get Annie to start the poll for a week

**Comment by caniszczyk** [comment]
so Annie didn't get to starting the poll, I'm just going to do it tomorrow, final call, poll will launch 2/21 and end 2/26, sorry for the delay on this, it's about time we follow the charter here :)

**Comment by caniszczyk** [comment]
The TSC is formed, thanks everyone who voted!

https://github.com/todogroup/charter/blob/master/README.md#todo-steering-committee-tsc

Poll results here: http://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=5&id=E_e1fedf84d0c918dd&algorithm=runoff

**Comment by jimjag** [comment]
I was left off the poll, but that's OK :)

**Comment by caniszczyk** [comment]
@jimjag I had another capital one rep in your place (Jared): https://github.com/todogroup/charter/blob/master/MEMBERS.csv

I'm going to update MEMBERS to reflect primary reps + alternatives

**Comment by jimjag** [comment]
Yeah, I saw, but wasn't sure why since I had "asked first", and assumed that the listing would be in chronological order... I didn't want to bother before and during the poll, but now that its done, I was just... curious... :)
